\connect leqvo;

ALTER TABLE deposits
  ADD COLUMN IF NOT EXISTS price_amount NUMERIC(18, 8) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS actually_paid NUMERIC(18, 8) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS actually_paid_at_fiat NUMERIC(18, 8) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS credited_at TIMESTAMPTZ;
